server:
  port: 8083
spring:
  application:
    name: PRODUCT-INVENTORY
eureka:
  client:
    service-url:
     default-zone: http://EUREKA-REGISTRY
    
  instance:
    hostname: localhost       