server:
  port: 8081
spring:
  application:
    name: PRODUCT-CATALOG
eureka:
  client:
    service-url:
     default-zone: http://EUREKA-REGISTRY
    
  instance:
    hostname: localhost       