server:
  port: 8082
spring:
  application:
    name: PRODUCT-INFO
eureka:
  client:
    service-url:
     default-zone: http://EUREKA-REGISTRY
    
  instance:
    hostname: localhost       